### ISSUE TITLE
samFilter: /lib64/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by lkong888** [y9c/pseudoU-BIDseq#4] opened 2023-10-09 12:21 UTC
Hi, may I ask what's the dependency for samFilter? The following error shows when executing the samFilter file under bin directory. 
 /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /users/ludwig/ebu571/ebu571/BIDseq/pseudoU-BIDseq-main/bin/samFilter)
 /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /users/ludwig/ebu571/ebu571/BIDseq/pseudoU-BIDseq-main/bin/samFilter)
 /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /users/ludwig/ebu571/ebu571/BIDseq/pseudoU-BIDseq-main/bin/samFilter).
Thanks.

**Comment by y9c** [comment] 2023-10-10 11:45
Hi @lkong888, tis error is caused by the dependency of the gcc environment. You might use the legacy version of linux system. Coud you provide more details with the command you use and the version of your Linux?

**Comment by lkong888** [comment] 2023-10-10 15:34
Hi @y9c , thank you so much for your reply. So, I downloaded the source code of this package, supplied it with the path of required packages(such as bowtie2, star), modified corresponding config file, and then ran the snakefile. Everything goes fine. But it turns out some executable file under the bin/ directory are binary and unable to be executed successfully(including samFilter and deletionFilter). Both show the same errors:  /lib64/libc.so.6: version `GLIBC_2.28' not found; /lib64/libc.so.6: version `GLIBC_2.18' not found and /lib64/libc.so.6: version `GLIBC_2.25' not found.  I further checked and found that /lib64/libc.so.6 corresponds to libc-2.17.so.  I think this might not be a good way to run your packages. But it would be great if samFilter and deletionFilter are readable files.

Another way to run your tool is "apptainer run docker://y9ch/bidseq", which is very neat. I'm running under "BIDseq" directory, which contains a fastq directory, a resource directory, bidseq_latest.sif and data.yaml. However, somehow it shows error saying that data.yaml can not be found! shouldn't data.yaml be at current working directory("BIDseq" in my case) according to the instructions?

I'd greatly appreciate it if you could help me with this problems. Thank you so much!

**Comment by lkong888** [comment] 2023-10-10 15:59
Thank you so much for your promt reply. the working sirectory is "/users/ludwig/ebu571/ebu571/BIDseq".(output from pwd)
The output of df is:
Filesystem                                                                                                                                 1K-blocks          Used     Available Use% Mounted on
devtmpfs                                                                                                                                   197401632             0     197401632   0% /dev
tmpfs                                                                                                                                      197414444           344     197414100   1% /dev/shm
tmpfs                                                                                                                                      197414444       2066016     195348428   2% /run
tmpfs                                                                                                                                      197414444             0     197414444   0% /sys/fs/cgroup
/dev/mapper/system-root                                                                                                                     41922560      11887632      30034928  29% /
/dev/sda1                                                                                                                                     999320        244444        686064  27% /boot
/dev/mapper/system-tmp                                                                                                                     115880672      24202092      91678580  21% /tmp
/dev/mapper/system-var                                                                                                                      41922560      13709344      28213216  33% /var
arc3-ib:/data/arc3a/PROCARDIS                                                                                                            41943040000   40298859520    1644180480  97% /arc/PROCARDIS
arc4-ib:/data/arc4e/ckb                                                                                                                  36700160000   19307322368   17392837632  53% /arc/ckb
arc4-ib:/data/arc4e/jones                                                                                                                28311552000   27968046080     343505920  99% /arc/jones
arc4-ib:/data/arc4e/zhang                                                                                                               130023424000  128974902272    1048521728 100% /arc/zhang
arc4-ib:/data/arc4e/siebold                                                                                                               2097152000    1659095040     438056960  80% /arc/siebold
arc4-ib:/srv/lamb                                                                                                                           41922560       9348096      32574464  23% /arc/lamb
arc4-ib:/data/arc4e/gilbert                                                                                                              33554432000   32849651712     704780288  98% /arc/gilbert
bowmore-ib:/data/bowmore2                                                                                                              1093772779520 1087084765184    6688014336 100% /data/bowmore2
bowmore-ib:/data/bowmore                                                                                                                488293539840  427964615680   60328924160  88% /data/bowmore
10.128.0.11@tcp,10.128.0.12@tcp:10.128.0.13@tcp,10.128.0.14@tcp:10.128.0.15@tcp,10.128.0.16@tcp:10.128.0.17@tcp,10.128.0.18@tcp:/exafs 4875413354112 2201522321108 2428854818668  48% /exafs1
WTGPFS3                                                                                                                                8304319266816 6264249810944 2040069455872  76% /gpfs3
WTGPFS2                                                                                                                                3835196080128 3310553634816  524642445312  87% /gpfs2
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37786
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37756
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/31010
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38275
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38616
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37936
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37628
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37014
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38544
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38676
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38486
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34807
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38252
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38805
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34713
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38554
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38318
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34881
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38587
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38342
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38635
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37959
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38334
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38199
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37925
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38296
tmpfs                                                                                                                                       39482892             4      39482888   1% /run/user/34854
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38274
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4406
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38291
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37871
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34817
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37336
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38048
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38798
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/2947
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34858
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4142
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4332
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38715
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37604
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38455
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38808
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38392
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/3967
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37099
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38648
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37884
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34705
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37155
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4284
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34828
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37919
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37121
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37286
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/30111
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38359
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38248
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37957
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34926
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38786
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/30132
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37796
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37726
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38557
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34872
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34884
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38131
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34799
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37106
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34853
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37264
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4233
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38473
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/2658
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34932
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38567
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4417
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37406
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37215
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38568
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37981
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38360
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37315
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38128
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/2503
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38788
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38477
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37295
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38804
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38332
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/3032
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38556
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38215
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38659
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37053
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/3891
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38658
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37686
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38633
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34694
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38570
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34857
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/4244
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38224
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37876
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37942
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38750
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38251
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38097
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38772
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38611
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38784
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37352
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37044
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/3232
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38509
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37970
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38072
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37090
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/30046
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38613
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34718
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37469
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38503
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37951
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38304
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38722
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38576
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38137
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38652
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34700
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37290
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38336
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38601
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37288
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37887
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38406
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/30094
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38584
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38589
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38448
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34905
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/3623
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38262
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38161
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38095
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37510
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/34906
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38707
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37094
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38169
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/38302
tmpfs                                                                                                                                       39482892             0      39482892   0% /run/user/37869

**Comment by y9c** [comment] 2023-10-10 16:10
I am not sure if /users/ludwig directory is a soft link or not based on the provided information. But you can try adding `--bind /users/ludwig/ebu571` or `--bind /users` into the command right after 'run'.

**Comment by y9c** [comment] 2023-10-10 16:24
How about try realpath data.yaml for more details

**Comment by lkong888** [comment] 2023-10-10 16:36
Hi,

Both "apptainer run --bind /users/ludwig/ebu571 docker://y9ch/bidseq " and "apptainer run --bind /users docker://y9ch/bidseq" do not work. 
For more detailed information,
current path: /users/ludwig/ebu571/ebu571/BIDseq (pwd)
realpath: /gpfs3/well/ludwig/users/ebu571/BIDseq (realpath /users/ludwig/ebu571/ebu571/BIDseq)
realpath of data.yaml: /gpfs3/well/ludwig/users/ebu571/BIDseq/data.yaml (realpath data.yaml).

Thanks.

**Comment by y9c** [comment] 2023-10-10 16:45
Yes. This is the bug we have mentioned in the previous thread. /gpfs3 is not exposed to appraiser.

Try --bind /gpfs3

**Comment by lkong888** [comment] 2023-10-10 17:02
apptainer run --bind /gpfs3 docker://y9ch/bidseq does not work. The same error keeps showing even when I replace --bind /gpfs3  with /gpfs3/well or /gpfs3/well/ludwig or /gpfs3/well/ludwig/users or /gpfs3/well/ludwig/users/ebu571. I also tried to give the realpath of data.yaml (apptainer run docker://y9ch/bidseq -c /gpfs3/well/ludwig/users/ebu571/BIDseq/data.yaml), but it still does not work.

**Comment by y9c** [comment] 2023-10-10 18:08
Thank you for the update. Some time Apptainer to not have the privilege to parse some path due to permission setting.
I guess you are running the code on HPC without root privilege. You might need to ask the manager to set up apptainer properly.

**Comment by y9c** [comment] 2023-10-10 19:28
Hi Kong, if possible we can have another attempt to run the code. Based on your input, I guess your server have a complex directory structure. `--bind /gpfs3/well/ludwig/users:/users/ludwig/ebu571` might works

**Comment by lkong888** [comment] 2023-10-10 19:49
Hi,

That's great. With " --bind /gpfs3/well/ludwig/users:/users/ludwig/ebu571 ", apptainer can find the data.yaml successfully. But it shows the following errors:
Traceback (most recent call last):
  File "/pipeline/micromamba/lib/python3.10/site-packages/snakemake/__init__.py", line 564, in snakemake
    workflow = Workflow(
  File "/pipeline/micromamba/lib/python3.10/site-packages/snakemake/workflow.py", line 242, in __init__
    self.sourcecache = SourceCache()
  File "/pipeline/micromamba/lib/python3.10/site-packages/snakemake/sourcecache.py", line 336, in __init__
    os.makedirs(self.cache, exist_ok=True)
  File "/pipeline/micromamba/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/pipeline/micromamba/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/pipeline/micromamba/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/pipeline/micromamba/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/users/ludwig/ebu571/.cache'

I think the cmd tries to make a directory under '/users/ludwig/ebu571/.cache', but the permission is denied. I guess I may need to consult the manager tomorrow.

Thank you so much for the troubleshooting. it's very helpful.

**Comment by y9c** [comment] 2023-10-10 20:02
Great to known. The permission management of this sever is a little bit complicated. You can try `--bind /gpfs3/well/ludwig/users/ebu571/BIDseq:/users/ludwig/ebu571/ebu571/BIDseq`

**Comment by lkong888** [comment] 2023-10-10 20:11
Yes, the directory structure system is quite complicated. 
With "apptainer run --bind /gpfs3/well/ludwig/users/ebu571/BIDseq:/users/ludwig/ebu571/ebu571/BIDseq docker://y9ch/bidseq", it fails to find the data.yaml again. 

 Is it possible to specify a place(eg, /gpfs3/well/ludwig/users/ebu571) instead of "/users/ludwig/ebu571" to make the directory?

**Comment by y9c** [comment] 2023-10-14 05:02
Hi, @lkong888. Thank you very much for posting the error log for debug. I believe that now the problem is on the Linux server side. I would like to close this issue first and you can report or share your findings in new issue.

**Closed by y9c** 2023-10-14 05:02 UTC
